build:
  version: "2.0"

cards:
  message: "Welcome to Bank cards related QA APIs"
  contactDetails:
    name: "Saquib Khan - Developer"
    email: "ksaquib54@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345