build:
  version: "3.0"

loans:
  message: "Welcome to Bank loans related QA APIs"
  contactDetails:
    name: "Saquib Khan - Developer"
    email: "ksaquib54@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345